
import Link from "next/link";
import "./globals.css";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
      <nav>
        <Link href="/">Home</Link> 
        <Link href="/product">Product</Link>
        <Link href="/contact">Contact</Link>
        <Link href="/dashboard">Dashboard</Link>
      </nav>

        {children}
      </body>
    </html>
  );
}
